# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'video_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x05video\"\"\n\x0cVideoRequest\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"#\n\rVideoResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x32M\n\x0cVideoService\x12=\n\x0cProcessVideo\x12\x13.video.VideoRequest\x1a\x14.video.VideoResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=30
  _globals['_VIDEOREQUEST']._serialized_end=64
  _globals['_VIDEORESPONSE']._serialized_start=66
  _globals['_VIDEORESPONSE']._serialized_end=101
  _globals['_VIDEOSERVICE']._serialized_start=103
  _globals['_VIDEOSERVICE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
